Repository czbiohub-sf/shrimPy, pull requests merged in 2024-07, with the labels that each got.

#134 Fix t_idx and additional channels
  mantis/analysis/register.py
  mantis/cli/apply_affine.py
  mantis/cli/estimate_affine.py
  mantis/cli/utils.py
Labels: bug, analysis

#150 Improve registration docs and naming
  README.md
  examples/slurmkit_example/slurm_apply_affine.py
  mantis/analysis/settings/example_register_settings.yml
  mantis/cli/estimate_registration.py
  mantis/cli/main.py
  mantis/cli/optimize_registration.py
  mantis/cli/register.py
  mantis/tests/conftest.py
  mantis/tests/test_analysis/test_analysis_settings.py
  mantis/tests/test_cli/test_optimize_affine.py
  mantis/tests/test_cli/test_register_cli.py
Labels: documentation

#154 adding configurable CZYX chunk size
  mantis/analysis/AnalysisSettings.py
  mantis/analysis/settings/example_concatenate_settings.yml
  mantis/cli/concatenate.py
Labels: enhancement
